class Failure {
  final String message;
  const Failure({this.message = 'an unexpected error occured'});
}
